name: ubuntu18.04

on:
  push:
    branches: [ stable action ]
  pull_request:
    branches: [ stable ]

jobs:
  test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: check versions
      run: |
        echo `gcc --version`
    - name: fetch google test
      run: |
        wget https://github.com/google/googletest/archive/release-1.10.0.zip
    - name: prepare install dir
      run: mkdir lib/
    - name: install google test
      run: |
        unzip release-1.10.0.zip
        mkdir googletest-release-1.10.0/build && cd googletest-release-1.10.0/build
        cmake -DCMAKE_INSTALL_PREFIX=../../lib/ ../ && make -j4
        make install
    - name: build tinyles
      run: |
        mkdir build && cd build
        cmake -DCMAKE_PREFIX_PATH=../lib/ ../
        make -j4
    - name: test tinylex
      run: |
        ./build/test_code/test_tinylex
